In [253]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [254]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [255]:
df.shape

(569, 33)

In [256]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [257]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [258]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2,random_state=42)

In [259]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [260]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [261]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [262]:
X_train_tensor.shape

torch.Size([455, 30])

# Defining the model

In [263]:
# class MySimpleNN()
  #initialize

  #forward function

  #loss function


class MySimpleNN():

  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward_pass(self,X):
    Z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(Z)
    return y_pred

  def loss_function(self,y_pred,y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss


      # def loss_function(self, y_pred, y):
      #   criterion = torch.nn.BCELoss()
      #   loss = criterion(y_pred, y)
      #   return loss

In [264]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [265]:
# create model
torch.manual_seed(42)
model=MySimpleNN(X_train_tensor)

#epoch loop
for epoch in range(epochs):
  # forward pass
  y_pred=model.forward_pass(X_train_tensor)

  # loss
  loss=model.loss_function(y_pred,y_train_tensor)

  # backward pass
  loss.backward()

  # param update
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  # zero grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 2.9615699828457833
Epoch: 2, Loss: 2.8131138964342184
Epoch: 3, Loss: 2.6646426866228032
Epoch: 4, Loss: 2.5100000196924688
Epoch: 5, Loss: 2.350565750514645
Epoch: 6, Loss: 2.1948220587223157
Epoch: 7, Loss: 2.041202943133097
Epoch: 8, Loss: 1.8887141852208467
Epoch: 9, Loss: 1.74105313797397
Epoch: 10, Loss: 1.5995104593170377
Epoch: 11, Loss: 1.4694172242025978
Epoch: 12, Loss: 1.3495022527245604
Epoch: 13, Loss: 1.2372197313390139
Epoch: 14, Loss: 1.1393332310137823
Epoch: 15, Loss: 1.057799606987682
Epoch: 16, Loss: 0.9917333787414774
Epoch: 17, Loss: 0.9393425388036476
Epoch: 18, Loss: 0.8982718868958073
Epoch: 19, Loss: 0.866083022079926
Epoch: 20, Loss: 0.8406139677094522
Epoch: 21, Loss: 0.8201319124168504
Epoch: 22, Loss: 0.8033363650325822
Epoch: 23, Loss: 0.7892919273911199
Epoch: 24, Loss: 0.7773422595804
Epoch: 25, Loss: 0.7670303915970541

In [266]:
model.weights

tensor([[-0.2366],
        [-0.2269],
        [-0.1969],
        [-0.2534],
        [ 0.1792],
        [-0.0453],
        [ 0.4096],
        [ 0.4199],
        [-0.2638],
        [-0.1527],
        [-0.2688],
        [ 0.0664],
        [ 0.4055],
        [ 0.5299],
        [ 0.0981],
        [ 0.1219],
        [-0.3387],
        [ 0.1708],
        [ 0.3091],
        [ 0.0515],
        [-0.2516],
        [ 0.4057],
        [-0.0397],
        [-0.0200],
        [-0.2352],
        [-0.3692],
        [ 0.4720],
        [-0.3009],
        [ 0.0420],
        [-0.1844]], dtype=torch.float64, requires_grad=True)

# Evaluation

In [269]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward_pass(X_test_tensor)
  y_pred = (y_pred > 0.8).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6120344996452332