In [69]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [70]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [71]:
df.shape

(569, 33)

In [72]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [73]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [74]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2,random_state=42)

In [75]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [76]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [77]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train).to(torch.float64)
y_test_tensor = torch.from_numpy(y_test).to(torch.float64)

In [78]:
X_train_tensor.shape,y_train_tensor.shape

(torch.Size([455, 30]), torch.Size([455]))

In [79]:
X_test_tensor.dtype,y_test_tensor.dtype

(torch.float64, torch.float64)

# Defining the model

In [80]:
import torch.nn as nn

In [81]:
# class MySimpleNN()
  #initialize

  #forward function

  #loss function


class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()

    self.layer=nn.Linear(num_features,1,dtype=torch.float64)
    self.activation=nn.Sigmoid()
    self.criterion=nn.BCELoss()

  def forward(self,features):
    z=self.layer(features)
    out=self.activation(z)
    return out

  def loss_function(self,y_pred,y):
    loss=self.criterion(y_pred,y)
    return loss

In [82]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [85]:
# create model
torch.manual_seed(42)
model=MySimpleNN(X_train_tensor.shape[1])

#create optimizer
optim=torch.optim.SGD(model.parameters(),lr=learning_rate)

#epoch loop
for epoch in range(epochs):
  # forward pass
  y_pred=model.forward(X_train_tensor)

  # loss
  loss=model.loss_function(y_pred,y_train_tensor.reshape(-1,1))

  # backward pass
  loss.backward()

  # param update
  optim.step()

  # zero grad

  optim.zero_grad()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 1.028801017818049
Epoch: 2, Loss: 0.706489602134738
Epoch: 3, Loss: 0.5397522790349313
Epoch: 4, Loss: 0.44914796760523484
Epoch: 5, Loss: 0.39286566685708
Epoch: 6, Loss: 0.3541898615589234
Epoch: 7, Loss: 0.32569288538617147
Epoch: 8, Loss: 0.3036278270755398
Epoch: 9, Loss: 0.28590543267393365
Epoch: 10, Loss: 0.27126789417954406
Epoch: 11, Loss: 0.2589112569712606
Epoch: 12, Loss: 0.2482964430436614
Epoch: 13, Loss: 0.23904752337873436
Epoch: 14, Loss: 0.23089361548770765
Epoch: 15, Loss: 0.22363403322584277
Epoch: 16, Loss: 0.2171165071272827
Epoch: 17, Loss: 0.2112230889561205
Epoch: 18, Loss: 0.20586075005148655
Epoch: 19, Loss: 0.20095494295033187
Epoch: 20, Loss: 0.1964450882713928
Epoch: 21, Loss: 0.19228134443668904
Epoch: 22, Loss: 0.18842225157095965
Epoch: 23, Loss: 0.18483298324050507
Epoch: 24, Loss: 0.18148402865931593
Epoch: 25, Loss: 0.1783501849224679

In [92]:
model.layer.weight,model.layer.bias

(Parameter containing:
 tensor([[ 0.1212,  0.0551,  0.1462,  0.1079,  0.1532,  0.1689,  0.3855,  0.4439,
          -0.0217, -0.1805,  0.0663, -0.0613,  0.2982,  0.3192, -0.0700,  0.0412,
          -0.1742,  0.1327,  0.0065, -0.0929,  0.1595,  0.3221,  0.2412,  0.2222,
           0.0506,  0.0468,  0.3830,  0.1776,  0.1402, -0.0118]],
        dtype=torch.float64, requires_grad=True),
 Parameter containing:
 tensor([-0.2446], dtype=torch.float64, requires_grad=True))

# Evaluation

In [99]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.6).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5387811660766602