In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [70]:
df=pd.read_csv('CarPrice_Assignment.csv')

df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [71]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [72]:
df.drop(['car_ID','symboling','CarName'],axis=1,inplace=True)

df

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [73]:
X=df.drop('price',axis=1)
y=df['price']

In [74]:
X

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
1,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
2,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,...,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26
3,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,...,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30
4,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,...,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28
201,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5,...,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25
202,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23
203,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,six,145,idi,3.01,3.40,23.0,106,4800,26,27
204,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25

In [75]:
y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

In [76]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [77]:
X_train
# X_test
# y_train
# y_test

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
66,diesel,std,four,sedan,rwd,front,104.9,175.0,66.1,54.4,...,four,134,idi,3.43,3.64,22.0,72,4200,31,39
111,gas,std,four,sedan,rwd,front,107.9,186.7,68.4,56.7,...,four,120,mpfi,3.46,2.19,8.4,95,5000,19,24
153,gas,std,four,wagon,fwd,front,95.7,169.7,63.6,59.1,...,four,92,2bbl,3.05,3.03,9.0,62,4800,31,37
96,gas,std,four,sedan,fwd,front,94.5,165.3,63.8,54.5,...,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37
38,gas,std,two,hatchback,fwd,front,96.5,167.5,65.2,53.3,...,four,110,1bbl,3.15,3.58,9.0,86,5800,27,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,gas,std,two,hatchback,rwd,front,99.2,178.5,67.9,49.7,...,six,181,mpfi,3.43,3.27,9.0,160,5200,19,25
14,gas,std,four,sedan,rwd,front,103.5,189.0,66.9,55.7,...,six,164,mpfi,3.31,3.19,9.0,121,4250,20,25
92,gas,std,four,sedan,fwd,front,94.5,165.3,63.8,54.5,...,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37
179,gas,std,two,hatchback,rwd,front,102.9,183.5,67.7,52.0,...,six,171,mpfi,3.27,3.35,9.3,161,5200,19,24
102,gas,std,four,wagon,fwd,front,100.4,184.6,66.5,56.1,...,six,181,mpfi,3.43,3.27,9.0,152,5200,17,22

In [78]:
X_train['fueltype'].describe()

count     164
unique      2
top       gas
freq      149
Name: fueltype, dtype: object

In [79]:
X_train['fueltype'].value_counts()

fueltype
gas       149
diesel     15
Name: count, dtype: int64

In [80]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

fuel_enc=OrdinalEncoder(categories=[['gas','diesel']],handle_unknown='use_encoded_value',unknown_value=-1)
X_train['fueltype']=fuel_enc.fit_transform(X_train[['fueltype']]).ravel()
X_test['fueltype']=fuel_enc.transform(X_test[['fueltype']]).ravel()

In [81]:
X_train['fueltype'].value_counts()

fueltype
0.0    149
1.0     15
Name: count, dtype: int64

In [82]:
X_test['fueltype'].value_counts()

fueltype
0.0    36
1.0     5
Name: count, dtype: int64

In [83]:
df['drivewheel'].value_counts()

drivewheel
fwd    120
rwd     76
4wd      9
Name: count, dtype: int64

In [84]:
from sklearn.base import TransformerMixin
ohe=OneHotEncoder(sparse_output=False,handle_unknown='ignore').set_output(transform='pandas')

train_enc=ohe.fit_transform(X_train[['drivewheel']])

train_enc

     drivewheel_4wd  drivewheel_fwd  drivewheel_rwd
66              0.0             0.0             1.0
111             0.0             0.0             1.0
153             0.0             1.0             0.0
96              0.0             1.0             0.0
38              0.0             1.0             0.0
..              ...             ...             ...
106             0.0             0.0             1.0
14              0.0             0.0             1.0
92              0.0             1.0             0.0
179             0.0             0.0             1.0
102             0.0             1.0             0.0

[164 rows x 3 columns]

In [85]:
test_enc=ohe.transform(X_test[['drivewheel']])

In [86]:
X_train=pd.concat([X_train,train_enc],axis=1)
X_test=pd.concat([X_test,test_enc],axis=1)

In [87]:
X_train.drop('drivewheel',axis=1,inplace=True)
X_test.drop('drivewheel',axis=1,inplace=True)

In [88]:
X_train

,fueltype,aspiration,doornumber,carbody,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,...,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,drivewheel_4wd,drivewheel_fwd,drivewheel_rwd
66,1.0,std,four,sedan,front,104.9,175.0,66.1,54.4,2700,...,3.43,3.64,22.0,72,4200,31,39,0.0,0.0,1.0
111,0.0,std,four,sedan,front,107.9,186.7,68.4,56.7,3075,...,3.46,2.19,8.4,95,5000,19,24,0.0,0.0,1.0
153,0.0,std,four,wagon,front,95.7,169.7,63.6,59.1,2280,...,3.05,3.03,9.0,62,4800,31,37,0.0,1.0,0.0
96,0.0,std,four,sedan,front,94.5,165.3,63.8,54.5,1971,...,3.15,3.29,9.4,69,5200,31,37,0.0,1.0,0.0
38,0.0,std,two,hatchback,front,96.5,167.5,65.2,53.3,2289,...,3.15,3.58,9.0,86,5800,27,33,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.0,std,two,hatchback,front,99.2,178.5,67.9,49.7,3139,...,3.43,3.27,9.0,160,5200,19,25,0.0,0.0,1.0
14,0.0,std,four,sedan,front,103.5,189.0,66.9,55.7,3055,...,3.31,3.19,9.0,121,4250,20,25,0.0,0.0,1.0
92,0.0,std,four,sedan,front,94.5,165.3,63.8,54.5,1938,...,3.15,3.29,9.4,69,5200,31,37,0.0,1.0,0.0
179,0.0,std,two,hatchback,front,102.9,183.5,67.7,52.0,3016,...,3.27,3.35,9.3,161,5200,19,24,0.0,0.0,1.0
102,0.0,std,four,wagon,front,100.4,184.6,66.5,56.1,3296,...,3.43,3.27,9.0,152,5200,17,22,0.0,1.0,0.0

In [89]:
X_test

,fueltype,aspiration,doornumber,carbody,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,...,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,drivewheel_4wd,drivewheel_fwd,drivewheel_rwd
15,0.0,std,four,sedan,front,103.5,189.0,66.9,55.7,3230,...,3.62,3.390,8.00,182,5400,16,22,0.0,0.0,1.0
9,0.0,turbo,two,hatchback,front,99.5,178.2,67.9,52.0,3053,...,3.13,3.400,7.00,160,5500,16,22,1.0,0.0,0.0
100,0.0,std,four,sedan,front,97.2,173.4,65.2,54.7,2302,...,3.33,3.470,8.50,97,5200,27,34,0.0,1.0,0.0
132,0.0,std,two,hatchback,front,99.1,186.6,66.5,56.1,2658,...,3.54,3.070,9.31,110,5250,21,28,0.0,1.0,0.0
68,1.0,turbo,four,wagon,front,110.0,190.9,70.3,58.7,3750,...,3.58,3.640,21.50,123,4350,22,25,0.0,0.0,1.0
95,0.0,std,two,hatchback,front,94.5,165.6,63.8,53.3,2028,...,3.15,3.290,9.40,69,5200,31,37,0.0,1.0,0.0
159,1.0,std,four,hatchback,front,95.7,166.3,64.4,52.8,2275,...,3.27,3.350,22.50,56,4500,38,47,0.0,1.0,0.0
162,0.0,std,four,sedan,front,95.7,166.3,64.4,52.8,2140,...,3.19,3.030,9.00,70,4800,28,34,0.0,1.0,0.0
147,0.0,std,four,wagon,front,97.0,173.5,65.4,53.0,2455,...,3.62,2.640,9.00,94,5200,25,31,0.0,1.0,0.0
182,1.0,std,two,sedan,front,97.3,171.7,65.5,55.7,2261,...,3.01,3.400,23.00,52,4800,37,46,0.0,1.0,0.0
191,0.0,std,four,sedan,front,100.4,180.2,66.9,55.1,2661,...,3.19,3.400,8.50,110,5500,19,24,0.0,1.0,0.0
164,0.0,std,two,hatchback,front,94.5,168.7,64.0,52.6,2204,...,3.19,3.030,9.00,70,4800,29,34,0.0,0.0,1.0
65,0.0,std,four,sedan,front,104.9,175.0,66.1,54.4,2670,...,3.76,3.160,8.00,120,5000,19,27,0.0,0.0,1.0
175,0.0,std,four,hatchback,front,102.4,175.6,66.5,53.9,2414,...,3.31,3.540,8.70,92,4200,27,32,0.0,1.0,0.0
73,0.0,std,four,sedan,front,120.9,208.1,71.7,56.7,3900,...,3.80,3.350,8.00,184,4500,14,16,0.0,0.0,1.0
152,0.0,std,four,hatchback,front,95.7,158.7,63.6,54.5,2015,...,3.05,3.030,9.00,62,4800,31,38,0.0,1.0,0.0
18,0.0,std,two,hatchback,front,88.4,141.1,60.3,53.2,1488,...,2.91,3.030,9.50,48,5100,47,53,0.0,1.0,0.0
82,0.0,turbo,two,hatchback,front,95.9,173.2,66.3,50.2,2833,...,3.58,3.860,7.00,145,5000,19,24,0.0,1.0,0.0
86,0.0,std,four,sedan,front,96.3,172.4,65.4,51.6,2405,...,3.35,3.460,8.50,88,5000,25,32,0.0,1.0,0.0
143,0.0,std,four,sedan,front,97.2,172.0,65.4,52.5,2340,...,3.62,2.640,9.00,94,5200,26,32,0.0,1.0,0.0
60,0.0,std,four,sedan,front,98.8,177.8,66.5,55.5,2410,...,3.39,3.390,8.60,84,4800,26,32,0.0,1.0,0.0
101,0.0,std,four,sedan,front,100.4,181.7,66.5,55.1,3095,...,3.43,3.270,9.00,152,5200,17,22,0.0,1.0,0.0
98,0.0,std,two,hardtop,front,95.1,162.4,63.8,53.3,2008,...,3.15,3.290,9.40,69,5200,31,37,0.0,1.0,0.0
30,0.0,std,two,hatchback,front,86.6,144.6,63.9,50.8,1713,...,2.91,3.410,9.60,58,4800,49,54,0.0,1.0,0.0
25,0.0,std,four,sedan,front,93.7,157.3,63.8,50.6,1989,...,2.97,3.230,9.40,68,5500,31,38,0.0,1.0,0.0
16,0.0,std,two,sedan,front,103.5,193.8,67.9,53.7,3380,...,3.62,3.390,8.00,182,5400,16,22,0.0,0.0,1.0
168,0.0,std,two,hardtop,front,98.4,176.2,65.6,52.0,2536,...,3.62,3.500,9.30,116,4800,24,30,0.0,0.0,1.0
195,0.0,std,four,wagon,front,104.3,188.8,67.2,57.5,3034,...,3.78,3.150,9.50,114,5400,23,28,0.0,0.0,1.0
97,0.0,std,four,wagon,front,94.5,170.2,63.8,53.5,2037,...,3.15,3.290,9.40,69,5200,31,37,0.0,1.0,0.0
194,0.0,std,four,sedan,front,104.3,188.8,67.2,56.2,2912,...,3.78,3.150,9.50,114,5400,23,28,0.0,0.0,1.0
67,1.0,turbo,four,sedan,front,110.0,190.9,70.3,56.5,3515,...,3.58,3.640,21.50,123,4350,22,25,0.0,0.0,1.0
120,0.0,std,four,hatchback,front,93.7,157.3,63.8,50.6,1967,...,2.97,3.230,9.40,68,5500,31,38,0.0,1.0,0.0
154,0.0,std,four,wagon,front,95.7,169.7,63.6,59.1,2290,...,3.05,3.030,9.00,62,4800,27,32,1.0,0.0,0.0
202,0.0,std,four,sedan,front,109.1,188.8,68.9,55.5,3012,...,3.58,2.870,8.80,134,5500,18,23,0.0,0.0,1.0
79,0.0,turbo,two,hatchback,front,93.0,157.3,63.8,50.8,2145,...,3.03,3.390,7.60,102,5500,24,30,0.0,1.0,0.0
69,1.0,turbo,two,hardtop,front,106.7,187.5,70.3,54.9,3495,...,3.58,3.640,21.50,123,4350,22,25,0.0,0.0,1.0
145,0.0,turbo,four,sedan,front,97.0,172.0,65.4,54.3,2510,...,3.62,2.640,7.70,111,4800,24,29,1.0,0.0,0.0
55,0.0,std,two,hatchback,front,95.3,169.0,65.7,49.6,2380,...,3.33,3.255,9.40,101,6000,17,23,0.0,0.0,1.0
45,0.0,std,four,sedan,front,94.5,155.9,63.6,52.0,1909,...,3.03,3.110,9.60,70,5400,38,43,0.0,1.0,0.0
84,0.0,turbo,two,hatchback,front,95.9,173.2,66.3,50.2,2926,...,3.59,3.860,7.00,145,5000,19,24,0.0,1.0,0.0
146,0.0,std,four,wagon,front,97.0,173.5,65.4,53.0,2290,...,3.62,2.640,9.00,82,4800,28,32,0.0,1.0,0.0