# ML Assignment 02
### Dataset: House Price Prediction Dataset
### Total Marks: 100

---

## Exam Instructions:
1. প্রথমে নিচের cell এ নিজের **নাম** এবং কোর্সে registration করা **ইমেইল** দিবে
2. Question wise numbering করে Text cell রাখবে এবং এর নিচে Code cell থাকবে, চেষ্টা করবে একটি code cell এ একটি question উত্তর দেওয়ার
3. Google Colab এর মধ্যে কোডগুলো করবে
4. এবং সেই ফাইলটি **'Anyone with the link' & 'View' Access** দিয়ে ফাইলটির Shareable Link টি সাবমিট করবে

---

**Question Dataset Link:** https://www.kaggle.com/datasets/prokshitha/home-value-insights

## Student Information

In [63]:
# Fill in your information
name = "Md. Ammar Hamim"           # Write your full name here
email = "ammarhamim7@gmail.com"          # Write your registered email here

print(f"Name  : {name}")
print(f"Email : {email}")

Name  : Md. Ammar Hamim
Email : ammarhamim7@gmail.com

In [64]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [65]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression,SGDRegressor
from sklearn.metrics import r2_score,root_mean_squared_error,mean_squared_error

---
## Question 1 (10 Marks)

Load the House Price dataset and display:
- Dataset shape
- First 10 rows
- 5 random samples

# Question 1

In [66]:
df=pd.read_csv("/content/house_price_regression_dataset.csv")

In [67]:
df.shape

(1000, 8)

In [68]:
df.head(10)

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
5,3944,5,3,1990,2.475930,2,8,8.797970e+05
6,3671,1,2,2012,4.911960,0,1,8.144279e+05
7,3419,1,1,1972,2.805281,1,1,7.034131e+05
8,630,3,3,1997,1.014286,1,8,1.738750e+05
9,2185,4,2,1981,3.941604,2,5,5.041765e+05

In [69]:
df.sample(5)

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
630,1260,4,2,1965,1.929626,2,9,278644.669337
890,4002,3,1,2010,1.073163,1,10,860129.729209
367,3751,5,3,1973,3.782587,2,1,839522.318604
701,2475,5,2,2011,4.235679,0,3,594005.006523
94,4340,5,3,1962,1.881070,0,10,903251.940561

---
## Question 2 (10 Marks)

Handle missing values and perform feature engineering:
- Impute missing numerical values using `SimpleImputer` with mean strategy
- Impute missing categorical values using most frequent strategy
- Drop columns with more than 50% missing values
- Perform train-test split with `test_size=0.2` and `random_state=42`

Display the shape of final train and test sets.

# Question 2

In [70]:
df.isnull().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

In [71]:
# droping cols with more than 50% missing
ct = 0.5 * len(df)
df = df.dropna(thresh=ct, axis=1)

In [72]:
df.columns

Index(['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size', 'Neighborhood_Quality', 'House_Price'],
      dtype='object')

In [73]:
# feature and target seperation
X=df.drop('House_Price',axis=1)
y=df['House_Price']

In [74]:
X

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
0,1360,2,1,1981,0.599637,0,5
1,4272,3,3,2016,4.753014,1,6
2,3592,1,2,2016,3.634823,0,9
3,966,1,2,1977,2.730667,1,8
4,4926,2,1,1993,4.699073,0,8
...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10
996,3179,1,2,1999,2.977123,1,10
997,2606,4,2,1962,4.055067,0,2
998,4723,5,2,1950,1.930921,0,7
999,3268,4,2,1983,3.108790,2,2

In [75]:
y

0      2.623829e+05
1      9.852609e+05
2      7.779774e+05
3      2.296989e+05
4      1.041741e+06
           ...
995    7.014940e+05
996    6.837232e+05
997    5.720240e+05
998    9.648653e+05
999    7.425993e+05
Name: House_Price, Length: 1000, dtype: float64

In [76]:
# train test split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [77]:
X_train

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
29,2028,2,3,1967,1.784790,2,2
535,3519,5,3,1966,4.009947,0,10
695,4507,2,3,2014,4.122337,0,7
557,3371,4,2,2000,1.580318,0,1
836,2871,5,1,1974,3.426914,2,6
...,...,...,...,...,...,...,...
106,2257,5,1,1968,3.131006,0,2
270,3894,3,2,1975,1.256532,0,5
860,1484,5,1,2010,1.246555,1,6
435,1865,4,2,1994,4.354220,0,7
102,1363,4,1,1977,4.408878,1,1

In [78]:
X_test

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
521,4012,3,1,2016,2.098092,1,5
737,2310,3,1,1988,1.369622,1,4
740,4708,1,3,1962,1.792970,1,8
660,4932,2,1,1972,4.479598,1,2
411,3646,1,1,1994,3.980987,0,9
...,...,...,...,...,...,...,...
408,3767,5,3,1981,1.520335,2,4
332,616,2,3,1965,3.461372,1,7
208,4491,4,2,1994,3.399155,0,4
613,1858,1,1,1996,4.546672,2,8
78,3195,1,1,1962,3.913258,2,1

In [79]:
X.columns

Index(['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size', 'Neighborhood_Quality'],
      dtype='object')

In [80]:
numerical_features = X.select_dtypes(include=['int64', 'float64']).drop(columns=['Neighborhood_Quality']).columns
numerical_features

Index(['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size'],
      dtype='object')

In [81]:
categorical_features=['Neighborhood_Quality']
categorical_features

['Neighborhood_Quality']

In [82]:
# numerical features imputing with mean
num_imputer=SimpleImputer(strategy='mean')
X_train[numerical_features]=num_imputer.fit_transform(X_train[numerical_features])
X_test[numerical_features]=num_imputer.transform(X_test[numerical_features])

In [83]:
X_train

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
29,2028.0,2.0,3.0,1967.0,1.784790,2.0,2
535,3519.0,5.0,3.0,1966.0,4.009947,0.0,10
695,4507.0,2.0,3.0,2014.0,4.122337,0.0,7
557,3371.0,4.0,2.0,2000.0,1.580318,0.0,1
836,2871.0,5.0,1.0,1974.0,3.426914,2.0,6
...,...,...,...,...,...,...,...
106,2257.0,5.0,1.0,1968.0,3.131006,0.0,2
270,3894.0,3.0,2.0,1975.0,1.256532,0.0,5
860,1484.0,5.0,1.0,2010.0,1.246555,1.0,6
435,1865.0,4.0,2.0,1994.0,4.354220,0.0,7
102,1363.0,4.0,1.0,1977.0,4.408878,1.0,1

In [84]:
#categorical imputing with most freq
cat_imputer=SimpleImputer(strategy='most_frequent')
X_train[categorical_features]=cat_imputer.fit_transform(X_train[categorical_features])
X_test[categorical_features]=cat_imputer.transform(X_test[categorical_features])

In [85]:
X_train

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
29,2028.0,2.0,3.0,1967.0,1.784790,2.0,2
535,3519.0,5.0,3.0,1966.0,4.009947,0.0,10
695,4507.0,2.0,3.0,2014.0,4.122337,0.0,7
557,3371.0,4.0,2.0,2000.0,1.580318,0.0,1
836,2871.0,5.0,1.0,1974.0,3.426914,2.0,6
...,...,...,...,...,...,...,...
106,2257.0,5.0,1.0,1968.0,3.131006,0.0,2
270,3894.0,3.0,2.0,1975.0,1.256532,0.0,5
860,1484.0,5.0,1.0,2010.0,1.246555,1.0,6
435,1865.0,4.0,2.0,1994.0,4.354220,0.0,7
102,1363.0,4.0,1.0,1977.0,4.408878,1.0,1

In [86]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((800, 7), (200, 7), (800,), (200,))

---
## Question 3 (20 Marks)

Implement **Simple Linear Regression** using **only NumPy** (no Scikit-Learn allowed):
- Compute slope (`m`) and intercept (`c`) using the Batch Gradient Descent
- Predict values for the test set
- Print the learned `m` and `c` values

Use `Square_Footage` as feature (X) and `House_Price` as target (y).

# Question 3

In [87]:
X_new_train=X_train['Square_Footage'].values
X_new_test=X_test['Square_Footage'].values
y_new_train=y_train.values
y_new_test=y_test.values

In [88]:
def compute_cost(X,y,w,b):
  m=X.shape[0]
  cost=0.0

  pred=w*X+b
  error=pred-y
  error_sqr=error**2
  cost=np.sum(error_sqr)


  cost = cost / (2 * m)

  return cost

In [89]:
print(compute_cost(X_new_train,y_new_train,w=0,b=0))
print(compute_cost(X_new_train,y_new_train,w=17,b=0))

223405897071.37628
189841923799.30716

In [90]:
def calculate_gradient(X,y,w,b):
  m=X.shape[0]
  dj_dw=0.0
  dj_db=0.0

  pred=w*X+b
  error=pred-y
  dj_dw=np.sum(error*X)
  dj_db=np.sum(error)

  return dj_dw/m, dj_db/m

In [91]:
print(calculate_gradient(X_new_train,y_new_train,w=0,b=0))
print(calculate_gradient(X_new_train,y_new_train,w=19,b=0))

(np.float64(-2054978150.6077423), np.float64(-618576.0544203855))
(np.float64(-1874753579.8327422), np.float64(-565111.9544203855))

In [92]:
def gradient_descent(X,y,w_input,b_input,max_iter,alpha):


  w = w_input
  b = b_input
  cost_memo=[]

  for i in range(max_iter):

    dj_dw,dj_db=calculate_gradient(X,y,w,b)
    w = w - alpha * dj_dw
    b = b - alpha * dj_db

    cost=compute_cost(X,y,w,b)
    cost_memo.append(cost)

    if i % 100 == 0:
      print(f"Iteration {i}: Cost {cost:0.4f}, w: {w:0.4f}, b: {b:0.4f}")


  return w,b

In [93]:
w_init=0
b_init=0
MAX_ITER=1000
ALPHA=0.00000001
w_final,b_final=gradient_descent(X_new_train,y_new_train,w_init,b_init,MAX_ITER,ALPHA)

Iteration 0: Cost 183179374986.2054, w: 20.5498, b: 0.0062
Iteration 100: Cost 806479753.2888, w: 216.6348, b: 0.0733
Iteration 200: Cost 806479270.6497, w: 216.6440, b: 0.0823
Iteration 300: Cost 806479190.3450, w: 216.6440, b: 0.0912
Iteration 400: Cost 806479110.0404, w: 216.6440, b: 0.1002
Iteration 500: Cost 806479029.7358, w: 216.6440, b: 0.1092
Iteration 600: Cost 806478949.4312, w: 216.6440, b: 0.1181
Iteration 700: Cost 806478869.1267, w: 216.6440, b: 0.1271
Iteration 800: Cost 806478788.8222, w: 216.6440, b: 0.1360
Iteration 900: Cost 806478708.5177, w: 216.6440, b: 0.1450

In [94]:
print(w_final,b_final)

216.64402648904004 0.15388085589545403

In [95]:
def predict(X,w,b):
  return w*X+b

In [96]:
y_pred=predict(X_new_test,w_final,b_final)
y_real=y_new_test

for i in range(10):
  print(f"Predicted = {y_pred[i]:0.4f}  ---->  Actual value = {y_real[i]:0.4f}")

Predicted = 869175.9882  ---->  Actual value = 901000.4882
Predicted = 500447.8551  ---->  Actual value = 494537.5115
Predicted = 1019960.2306  ---->  Actual value = 949404.2007
Predicted = 1068488.4925  ---->  Actual value = 1040389.0481
Predicted = 789884.2745  ---->  Actual value = 794010.0167
Predicted = 776885.6329  ---->  Actual value = 724033.5605
Predicted = 1004795.1487  ---->  Actual value = 998439.2371
Predicted = 894090.0512  ---->  Actual value = 909713.4350
Predicted = 819131.2180  ---->  Actual value = 792681.5184
Predicted = 919220.7583  ---->  Actual value = 947490.7775

---
## Question 4 (10 Marks)

Build a **ColumnTransformer** that applies:
- `StandardScaler` on numerical columns: `Square_Footage`, `Num_Bedrooms`, `Num_Bathrooms`
- `OneHotEncoder` on categorical column: `Neighborhood_Quality`

# Question 4

In [97]:
df.columns

Index(['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size', 'Neighborhood_Quality', 'House_Price'],
      dtype='object')

In [98]:
# converting the datatype to objecct so that ohe treats it correctly
X_train['Neighborhood_Quality']=X_train['Neighborhood_Quality'].astype(str)
X_test['Neighborhood_Quality']=X_test['Neighborhood_Quality'].astype(str)

In [99]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 800 entries, 29 to 102
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Square_Footage        800 non-null    float64
 1   Num_Bedrooms          800 non-null    float64
 2   Num_Bathrooms         800 non-null    float64
 3   Year_Built            800 non-null    float64
 4   Lot_Size              800 non-null    float64
 5   Garage_Size           800 non-null    float64
 6   Neighborhood_Quality  800 non-null    object
dtypes: float64(6), object(1)
memory usage: 50.0+ KB

In [100]:
numeric_features=['Square_Footage','Num_Bedrooms','Num_Bathrooms']
categoric_features=['Neighborhood_Quality']

preprocessor=ColumnTransformer(
    transformers=[
        ('std_scaler',StandardScaler(),numeric_features),
        ('ohe',OneHotEncoder(handle_unknown='ignore',sparse_output=False),categoric_features)
    ],
    remainder='drop',
    verbose_feature_names_out=False
)

preprocessor.set_output(transform='pandas')

ColumnTransformer(transformers=[('std_scaler', StandardScaler(),
                                 ['Square_Footage', 'Num_Bedrooms',
                                  'Num_Bathrooms']),
                                ('ohe',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['Neighborhood_Quality'])],
                  verbose_feature_names_out=False)

In [101]:
X_train_transformed=preprocessor.fit_transform(X_train)
X_test_transformed=preprocessor.transform(X_test)

X_train_transformed

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Neighborhood_Quality_1,Neighborhood_Quality_10,Neighborhood_Quality_2,Neighborhood_Quality_3,Neighborhood_Quality_4,Neighborhood_Quality_5,Neighborhood_Quality_6,Neighborhood_Quality_7,Neighborhood_Quality_8,Neighborhood_Quality_9
29,-0.627722,-0.681986,1.261133,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
535,0.563185,1.429971,1.261133,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
695,1.352331,-0.681986,1.261133,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
557,0.444973,0.725985,0.035244,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
836,0.045608,1.429971,-1.190644,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,-0.444813,1.429971,-1.190644,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
270,0.862709,0.022000,0.035244,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
860,-1.062232,1.429971,-1.190644,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
435,-0.757915,0.725985,0.035244,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
102,-1.158878,0.725985,-1.190644,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Question 5 (20 Marks)

Build a complete **Pipeline** using Scikit-Learn that includes:
- The `ColumnTransformer`
- `SGDRegressor` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

# Question 5

In [102]:
ETA=0.01
MAX_ITER=3000
ALPHA=0.001


sgd_pipeline=Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('model',SGDRegressor(
            eta0=ETA,
            max_iter=MAX_ITER,
            alpha=ALPHA,
            loss='squared_error',
            learning_rate='constant',
            random_state=42
        ))
    ]
)

sgd_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('std_scaler',
                                                  StandardScaler(),
                                                  ['Square_Footage',
                                                   'Num_Bedrooms',
                                                   'Num_Bathrooms']),
                                                 ('ohe',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Neighborhood_Quality'])],
                                   verbose_feature_names_out=False)),
                ('model',
                 SGDRegressor(alpha=0.001, learning_rate='constant',
                              max_iter=3000, random_state=42))])

In [103]:
y_pred_sgd=sgd_pipeline.predict(X_test)
y_real=y_test.values

rmse=root_mean_squared_error(y_real,y_pred_sgd)
r2=r2_score(y_real,y_pred_sgd)

print("SGDRegressor Pipeline Results")
print(f"  RMSE : {rmse:.4f}")
print(f"  R²   : {r2:.4f}")

SGDRegressor Pipeline Results
  RMSE : 29140.4935
  R²   : 0.9868

In [104]:
print("\nFirst 10 Predictions vs Actual:")

for i in range(10):
  print(f"Sample : {i}------> Predicted = {y_pred_sgd[i]}------> Actual = {y_real[i]}")

First 10 Predictions vs Actual:
Sample : 0------> Predicted = 850291.7810662912------> Actual = 901000.4882338208
Sample : 1------> Predicted = 508838.14058913884------> Actual = 494537.5115454976
Sample : 2------> Predicted = 984330.1229172761------> Actual = 949404.2006657254
Sample : 3------> Predicted = 1022629.3303211855------> Actual = 1040389.0481357794
Sample : 4------> Predicted = 761373.2435073131------> Actual = 794010.0167336396
Sample : 5------> Predicted = 766153.9637262076------> Actual = 724033.5604571347
Sample : 6------> Predicted = 1000152.6267689858------> Actual = 998439.2371139774
Sample : 7------> Predicted = 899480.129785764------> Actual = 909713.435000704
Sample : 8------> Predicted = 797438.7065087403------> Actual = 792681.5184200833
Sample : 9------> Predicted = 888549.8686063166------> Actual = 947490.777477816

---
## Question 6 (20 Marks)

Implement **Multiple Linear Regression** using **Scikit-Learn**:
- The `ColumnTransformer`
- `LinearRegression` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

# Question 6

In [105]:
lr_pipeline=Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('model',LinearRegression())
    ]
)

lr_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('std_scaler',
                                                  StandardScaler(),
                                                  ['Square_Footage',
                                                   'Num_Bedrooms',
                                                   'Num_Bathrooms']),
                                                 ('ohe',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Neighborhood_Quality'])],
                                   verbose_feature_names_out=False)),
                ('model', LinearRegression())])

In [106]:
y_pred_lr=lr_pipeline.predict(X_test)
y_real=y_test.values

rmse_lr=root_mean_squared_error(y_real,y_pred_lr)
r2_lr=r2_score(y_real,y_pred_lr)

print("Multiple Linear Regression Results")
print(f"  RMSE : {rmse_lr:.4f}")
print(f"  R²   : {r2_lr:.4f}")

Multiple Linear Regression Results
  RMSE : 29093.0752
  R²   : 0.9869

In [107]:
print("\nFirst 10 Predictions vs Actual:")

for i in range(10):
  print(f"Sample : {i}------> Predicted = {y_pred_lr[i]}------> Actual = {y_real[i]}")

First 10 Predictions vs Actual:
Sample : 0------> Predicted = 851409.1473265477------> Actual = 901000.4882338208
Sample : 1------> Predicted = 507641.03386969864------> Actual = 494537.5115454976
Sample : 2------> Predicted = 985990.3750316359------> Actual = 949404.2006657254
Sample : 3------> Predicted = 1022654.7065338424------> Actual = 1040389.0481357794
Sample : 4------> Predicted = 760698.1336568069------> Actual = 794010.0167336396
Sample : 5------> Predicted = 765782.3163809121------> Actual = 724033.5604571347
Sample : 6------> Predicted = 1005039.0963438316------> Actual = 998439.2371139774
Sample : 7------> Predicted = 903407.7817723617------> Actual = 909713.435000704
Sample : 8------> Predicted = 797971.1884095871------> Actual = 792681.5184200833
Sample : 9------> Predicted = 888850.4300376978------> Actual = 947490.777477816

---
## Question 7 (10 Marks) (You have to explore the topic and use the equation via Numpy)
### Dont use LLMs , You can use Documentation

Implement **Multiple Linear Regression** using **only NumPy**:
- Pick random 100 datas from the dataset
- Use the Normal Equation: `θ = (XᵀX)⁻¹ Xᵀy`
- Use `Square_Footage`, `Num_Bedrooms`, and `Num_Bathrooms` as features
- Print the learned coefficients (θ values)

#

# Question 7

documentation used: https://medium.com/analytics-vidhya/multiple-linear-regression-from-scratch-using-only-numpy-98fc010a1926

In [108]:
sample_df=df.sample(100,random_state=42)
X=sample_df[['Square_Footage','Num_Bedrooms','Num_Bathrooms']].values
y=sample_df['House_Price'].values

X=np.c_[np.ones(X.shape[0]),X] #adding bias

def normal_equation(X, Y):
    beta = np.dot((np.linalg.inv(np.dot(X.T,X))), np.dot(X.T,Y))

    return beta

def predict(X_test, beta):
    return np.dot(X_test, beta)

In [109]:
beta = normal_equation(X,y)
predictions = predict(X, beta)

print("Learned coefficients:")
print(f"Beta_0 (Intercept)      : {beta[0]}")
print(f"Beta_1 (Square_Footage) : {beta[1]}")
print(f"Beta_2 (Num_Bedrooms)   : {beta[2]}")
print(f"Beta_3 (Num_Bathrooms)  : {beta[3]}")

Learned coefficients:
Beta_0 (Intercept)      : 20888.259452179074
Beta_1 (Square_Footage) : 202.30820792026861
Beta_2 (Num_Bedrooms)   : 8303.281041200185
Beta_3 (Num_Bathrooms)  : 3020.328521726886

In [110]:
for i in range(10):
  print(f"Sample:{i}----> Predicted={predictions[i]}----> Actual={y[i]}")

Sample:0----> Predicted=860478.9612736242----> Actual=901000.4882338208
Sample:1----> Predicted=516150.39139332704----> Actual=494537.5115454976
Sample:2----> Predicted=990719.5689471845----> Actual=949404.2006657254
Sample:3----> Predicted=1038299.2315190712----> Actual=1040389.0481357794
Sample:4----> Predicted=769827.5950924054----> Actual=794010.0167336396
Sample:5----> Predicted=769012.7121801164----> Actual=724033.5604571347
Sample:6----> Predicted=1001467.8375163663----> Actual=998439.2371139774
Sample:7----> Predicted=903371.2957885823----> Actual=909713.435000704
Sample:8----> Predicted=805442.484202842----> Actual=792681.5184200833
Sample:9----> Predicted=898908.8762620061----> Actual=947490.777477816