# Titanic Survival Prediction
This notebook demonstrates a complete machine learning workflow to predict passenger survival on the Titanic using Logistic Regression.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,LabelEncoder,StandardScaler,MinMaxScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer


from sklearn.linear_model import LogisticRegression

## 1. Data Loading and Initial Exploration
First, we load the dataset and take a look at a few sample rows to understand the features we are working with.

In [2]:
df = pd.read_csv("titanic_data_updated.csv")
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
639,640,no,third,"Thorneycroft, Mr. Percival",male,NaN,1,0,376564,16.1000,NaN,S
365,366,no,third,"Adahl, Mr. Mauritz Nils Martin",male,30.0,0,0,C 7076,7.2500,NaN,S
266,267,no,third,"Panula, Mr. Ernesti Arvid",male,16.0,4,1,3101295,39.6875,NaN,S
659,660,no,first,"Newell, Mr. Arthur Webster",male,58.0,0,2,35273,113.2750,D48,C
359,360,yes,third,"Mockler, Miss. Helen Mary ""Ellie""",female,NaN,0,0,330980,7.8792,NaN,Q

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [3]:
df['Cabin'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Cabin
Non-Null Count  Dtype
--------------  -----
204 non-null    object
dtypes: object(1)
memory usage: 7.1+ KB

## 2. Feature Engineering
We create new features like `Family_Size` and extract the `Deck` from the `Cabin` column to provide more meaningful information to the model.

In [6]:
df['Family_Size'] = df['SibSp'] + df['Parch'] + 1
df['Cabin'] = df['Cabin'].fillna("Missing")

df['Deck'] = df['Cabin'].astype(str).str[0]
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Deck
17,18,yes,second,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,Missing,S,1,M
525,526,no,third,"Farrell, Mr. James",male,40.5,0,0,367232,7.7500,Missing,Q,1,M
721,722,no,third,"Jensen, Mr. Svend Lauritz",male,17.0,1,0,350048,7.0542,Missing,S,2,M
561,562,no,third,"Sivic, Mr. Husein",male,40.0,0,0,349251,7.8958,Missing,S,1,M
454,455,no,third,"Peduzzi, Mr. Joseph",male,NaN,0,0,A/5 2817,8.0500,Missing,S,1,M

In [7]:
df['Deck'].value_counts()

Deck
M    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [8]:
# Separate the features (X) from the target we want to predict (y)
# We drop 'Survived' from X because that's our answer key
X = df.drop('Survived', axis=1)

# y contains only the survival status
y = df['Survived']

In [9]:
# Split data: 80% for training the model and 20% for testing its accuracy
# 'stratify=y' ensures both sets have a similar percentage of survivors
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

## 4. Outlier Handling and Data Cleaning
We use Z-scores to remove extreme outliers in `Age` and 'clip' the `Fare` column to prevent extreme values from distorting our model's learning.

In [10]:
X_train

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Deck
692,693,third,"Lam, Mr. Ali",male,NaN,0,0,1601,56.4958,Missing,S,1,M
481,482,second,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0000,Missing,S,1,M
527,528,first,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S,1,C
855,856,third,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,Missing,S,2,M
801,802,second,"Collyer, Mrs. Harvey (Charlotte Annie Tate)",female,31.0,1,1,C.A. 31921,26.2500,Missing,S,3,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,360,third,"Mockler, Miss. Helen Mary ""Ellie""",female,NaN,0,0,330980,7.8792,Missing,Q,1,M
258,259,first,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,Missing,C,1,M
736,737,third,"Ford, Mrs. Edward (Margaret Ann Watson)",female,48.0,1,3,W./C. 6608,34.3750,Missing,S,5,M
462,463,first,"Gee, Mr. Arthur H",male,47.0,0,0,111320,38.5000,E63,S,1,E
507,508,first,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,Missing,S,1,M

In [12]:
mean_age=X_train['Age'].mean()
std_age=X_train['Age'].mean()

X_train['Z_score']=(X_train['Age']-mean_age)/std_age

musk=(abs(X_train['Z_score'])<=3)

X_train=X_train[musk]
y_train=y_train[musk]

In [17]:
#fare

q1=X_train['Fare'].quantile(0.25)
q3=X_train['Fare'].quantile(0.75)

iqr=q3-q1

lb=max(0,q1-1.5*iqr)
ub=q3+1.5*iqr

X_train['Fare']=X_train['Fare'].clip(lb,ub)

/tmp/ipykernel_1077/2404049884.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Fare']=X_train['Fare'].clip(lb,ub)

## 5. Building Preprocessing Pipelines
We create different pipelines for numerical and categorical data. This handles missing values (imputation) and scales the data so all features are on a similar range.

In [18]:
from warnings import simplefilter
p1=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='mean')),
        ('std_scaler',StandardScaler())
    ]
)

p2=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),
        ('scaler',MinMaxScaler())
    ]
)

In [21]:
p1

Pipeline(steps=[('imputer', SimpleImputer()), ('std_scaler', StandardScaler())])

In [22]:
p2

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', MinMaxScaler())])

In [23]:
categories = [['third','second','first']]

In [25]:
p3=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('encoder',OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore'))
    ]
)

p4=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('encoder',OrdinalEncoder(categories=categories)),
        ('scaler',MinMaxScaler())
    ]
)

In [26]:
preprocessor = ColumnTransformer(
    transformers=[
        ('pipeline_1',p1,['Age']),
        ('pipeline_2',p2,['Fare','Family_Size']),
        ('pipeline_3',p3,['Embarked','Sex','Deck']),
        ('pipeline_4',p4,['Pclass'])
    ],
    remainder='drop'
)
preprocessor

ColumnTransformer(transformers=[('pipeline_1',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('std_scaler',
                                                  StandardScaler())]),
                                 ['Age']),
                                ('pipeline_2',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Fare', 'Family_Size']),
                                ('pipeline_3',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Embarked', 'Sex', 'Deck']),
                                ('pipeline_4',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OrdinalEncoder(categories=[['third',
                                                                              'second',
                                                                              'first']])),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Pclass'])])

## 6. Label Encoding
We convert our target variable (`yes`/`no`) into numerical values (1/0) because machine learning models require numeric inputs.

In [30]:
le = LabelEncoder()

y_train=le.fit_transform(y_train)
y_test = le.transform(y_test)

## 7. Model Training
We combine the preprocessing and the Logistic Regression model into a single `lr_model` pipeline and fit it to our training data.

In [31]:
lr_model=Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('model',LogisticRegression(class_weight='balanced',max_iter=1000))
    ]
)

lr_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('pipeline_1',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('std_scaler',
                                                                   StandardScaler())]),
                                                  ['Age']),
                                                 ('pipeline_2',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Fare', 'Family_Size']),
                                                 ('pipeline_3',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(str...
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Embarked', 'Sex', 'Deck']),
                                                 ('pipeline_4',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['third',
                                                                                               'second',
                                                                                               'first']])),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Pclass'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [32]:
lr_model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('pipeline_1',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('std_scaler',
                                                                   StandardScaler())]),
                                                  ['Age']),
                                                 ('pipeline_2',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Fare', 'Family_Size']),
                                                 ('pipeline_3',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(str...
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Embarked', 'Sex', 'Deck']),
                                                 ('pipeline_4',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['third',
                                                                                               'second',
                                                                                               'first']])),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Pclass'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [33]:
print(lr_model['model'].coef_)
print(lr_model['model'].intercept_)
print(lr_model['model'].classes_)

[[-0.55677758  0.5311947  -0.97181134 -0.30077564 -0.31934779 -2.40470843
  -0.22812707 -0.34527844  0.36404756  0.65101841  0.44391813 -0.59776867
  -0.71236308 -0.34307425  1.49693631]]
[1.53243729]
[0 1]

In [34]:
# Use the trained model to predict if passengers in the test set survived
y_pred = lr_model.predict(X_test)

# Get the raw probability scores (e.g., 0.85 chance of death, 0.15 chance of survival)
lr_model.predict_proba(X_test)

array([[0.85500733, 0.14499267],
       [0.92174397, 0.07825603],
       [0.77369249, 0.22630751],
       [0.92448153, 0.07551847],
       [0.37791038, 0.62208962],
       [0.43632533, 0.56367467],
       [0.24788908, 0.75211092],
       [0.57571888, 0.42428112],
       [0.47321943, 0.52678057],
       [0.77864041, 0.22135959],
       [0.86133595, 0.13866405],
       [0.81957353, 0.18042647],
       [0.33870905, 0.66129095],
       [0.70642528, 0.29357472],
       [0.15667685, 0.84332315],
       [0.83774391, 0.16225609],
       [0.46525277, 0.53474723],
       [0.86327003, 0.13672997],
       [0.79527705, 0.20472295],
       [0.23382374, 0.76617626],
       [0.86327003, 0.13672997],
       [0.20023945, 0.79976055],
       [0.86414097, 0.13585903],
       [0.45576117, 0.54423883],
       [0.8597215 , 0.1402785 ],
       [0.0278666 , 0.9721334 ],
       [0.66153659, 0.33846341],
       [0.6184413 , 0.3815587 ],
       [0.81659893, 0.18340107],
       [0.81375603, 0.18624397],
       [0.88121668, 0.11878332],
       [0.01596441, 0.98403559],
       [0.85148177, 0.14851823],
       [0.62352221, 0.37647779],
       [0.77905097, 0.22094903],
       [0.7510209 , 0.2489791 ],
       [0.77293297, 0.22706703],
       [0.39722705, 0.60277295],
       [0.86133595, 0.13866405],
       [0.17876719, 0.82123281],
       [0.76965898, 0.23034102],
       [0.01519643, 0.98480357],
       [0.85276568, 0.14723432],
       [0.13921465, 0.86078535],
       [0.22983281, 0.77016719],
       [0.81829363, 0.18170637],
       [0.8619623 , 0.1380377 ],
       [0.48952816, 0.51047184],
       [0.15868756, 0.84131244],
       [0.20515935, 0.79484065],
       [0.04664718, 0.95335282],
       [0.3630874 , 0.6369126 ],
       [0.3595406 , 0.6404594 ],
       [0.74203658, 0.25796342],
       [0.01948505, 0.98051495],
       [0.84504218, 0.15495782],
       [0.87217047, 0.12782953],
       [0.27755226, 0.72244774],
       [0.28950561, 0.71049439],
       [0.59055903, 0.40944097],
       [0.31189494, 0.68810506],
       [0.28473865, 0.71526135],
       [0.78811747, 0.21188253],
       [0.82928723, 0.17071277],
       [0.41914746, 0.58085254],
       [0.30697381, 0.69302619],
       [0.05713427, 0.94286573],
       [0.87593612, 0.12406388],
       [0.57069063, 0.42930937],
       [0.69702109, 0.30297891],
       [0.09521336, 0.90478664],
       [0.82195513, 0.17804487],
       [0.42540653, 0.57459347],
       [0.02481009, 0.97518991],
       [0.76582949, 0.23417051],
       [0.92291577, 0.07708423],
       [0.88518492, 0.11481508],
       [0.85798884, 0.14201116],
       [0.58862482, 0.41137518],
       [0.30589183, 0.69410817],
       [0.80386198, 0.19613802],
       [0.82303529, 0.17696471],
       [0.8667242 , 0.1332758 ],
       [0.84531603, 0.15468397],
       [0.28554517, 0.71445483],
       [0.34071143, 0.65928857],
       [0.87105779, 0.12894221],
       [0.3812087 , 0.6187913 ],
       [0.3815033 , 0.6184967 ],
       [0.02261463, 0.97738537],
       [0.4427022 , 0.5572978 ],
       [0.44364119, 0.55635881],
       [0.91003652, 0.08996348],
       [0.86340849, 0.13659151],
       [0.53195437, 0.46804563],
       [0.18237594, 0.81762406],
       [0.36533535, 0.63466465],
       [0.86133595, 0.13866405],
       [0.88518492, 0.11481508],
       [0.84800319, 0.15199681],
       [0.74580903, 0.25419097],
       [0.01992766, 0.98007234],
       [0.35926324, 0.64073676],
       [0.09391886, 0.90608114],
       [0.84520405, 0.15479595],
       [0.3441116 , 0.6558884 ],
       [0.63283749, 0.36716251],
       [0.86340849, 0.13659151],
       [0.80660654, 0.19339346],
       [0.5399452 , 0.4600548 ],
       [0.86133595, 0.13866405],
       [0.9406429 , 0.0593571 ],
       [0.85025968, 0.14974032],
       [0.38024412, 0.61975588],
       [0.16985974, 0.83014026],
       [0.86133595, 0.13866405],
       [0.78382874, 0.21617126],
       [0.78627954, 0.21372046],
       [0.84512407, 0.15487593],
       [0.80899118, 0.19100882],
       [0.85499772, 0.14500228],
       [0.27187694, 0.72812306],
       [0.91596262, 0.08403738],
       [0.33042784, 0.66957216],
       [0.80071157, 0.19928843],
       [0.77317183, 0.22682817],
       [0.41117181, 0.58882819],
       [0.40144333, 0.59855667],
       [0.83733439, 0.16266561],
       [0.51672339, 0.48327661],
       [0.81366998, 0.18633002],
       [0.85509204, 0.14490796],
       [0.37791038, 0.62208962],
       [0.86214446, 0.13785554],
       [0.57799101, 0.42200899],
       [0.81067037, 0.18932963],
       [0.0269415 , 0.9730585 ],
       [0.86133595, 0.13866405],
       [0.35932894, 0.64067106],
       [0.86321388, 0.13678612],
       [0.42843898, 0.57156102],
       [0.78363125, 0.21636875],
       [0.21458921, 0.78541079],
       [0.51284316, 0.48715684],
       [0.78827396, 0.21172604],
       [0.60824083, 0.39175917],
       [0.86340849, 0.13659151],
       [0.71331124, 0.28668876],
       [0.10408932, 0.89591068],
       [0.13437183, 0.86562817],
       [0.85105323, 0.14894677],
       [0.67218936, 0.32781064],
       [0.01919001, 0.98080999],
       [0.2018236 , 0.7981764 ],
       [0.68503867, 0.31496133],
       [0.12694658, 0.87305342],
       [0.72082667, 0.27917333],
       [0.84843679, 0.15156321],
       [0.67945577, 0.32054423],
       [0.18509397, 0.81490603],
       [0.2430924 , 0.7569076 ],
       [0.06502614, 0.93497386],
       [0.35932894, 0.64067106],
       [0.10243365, 0.89756635],
       [0.0962857 , 0.9037143 ],
       [0.31184555, 0.68815445],
       [0.86638347, 0.13361653],
       [0.43367721, 0.56632279],
       [0.17199469, 0.82800531],
       [0.33049507, 0.66950493],
       [0.9094642 , 0.0905358 ],
       [0.82195513, 0.17804487],
       [0.46922296, 0.53077704],
       [0.805065  , 0.194935  ],
       [0.18344375, 0.81655625],
       [0.81258527, 0.18741473],
       [0.73224889, 0.26775111],
       [0.04689516, 0.95310484],
       [0.78232635, 0.21767365]])

## 8. Evaluation
Finally, we evaluate the model using accuracy, precision, and recall to see how well it performs on the test set.

In [35]:
from sklearn.metrics import accuracy_score,precision_score,recall_score

In [36]:
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)
precision = precision_score(y_test,y_pred)
print(precision)
recall = recall_score(y_test,y_pred)
print(recall)

0.7653631284916201
0.6753246753246753
0.7536231884057971